version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:5000

  api-service:
    build: ./api-service
    ports:
      - "5000:5000"
    environment:
      - ML_SERVICE_URL=http://ml-service:8000
      - MONGO_URI=mongodb://mongodb:27017/

  ml-service:
    build: ./ml-service
    ports:
      - "8000:8000"

  worker-service:
    build: ./worker-service
    environment:
      - ML_SERVICE_URL=http://ml-service:8000

  mongodb:
    image: mongo:7.0
    ports:
      - "27018:27017"

  redis:
    image: redis:7.2-alpine
    ports:
      - "6379:6379"